name: Fragment
description: Fragment is a advanced permission system for SpigotMC & PaperMC
main: me.xemu.fragment.FragmentPlugin
version: 1.1.0
api-version: 1.13
authors: ["Xemu"]
softdepend:
  - PlaceholderAPI

commands:
  fragment:
    description: Fragment Command